run-dev-server:
	python manage.py runserver --settings config.settings.development

run-migrate:run-makemigrate
	python manage.py migrate --settings config.settings.development

run-makemigrate:
	python manage.py makemigrations --settings config.settings.development

exec-shell:
	python manage.py shell --settings config.settings.development